[tool.poetry]
name = "seo-audit-ai"
version = "0.1.0"
description = "SEO Audit AI tool"
authors = ["Maruca911 <lh@koikoi.asia>"] 

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.0"
matplotlib = "^3.8.0"
gunicorn = "^23.0.0"
