services:
  - type: web
    name: seo-audit-ai
    env: python
    buildCommand: "export PATH=/opt/render/project/poetry/bin:$PATH && poetry install"
    startCommand: "export PATH=/opt/render/project/poetry/bin:$PATH && poetry run gunicorn --bind 0.0.0.0:$PORT app:app"
    plan: free
